spring:
  application:
    name: base-feign
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/knowledge
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
      cache: false
#      prefix: classpath:/templates
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8022
feign:
  hystrix:
    enabled: true