spring:
  application:
    name: system-web
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowledge
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#为了模拟集群 端口采用控制台输入的形式写入
server:
  port: 9001

redis:
# Redis数据库索引（默认为0）
  database: 0
# Redis服务器地址
  host: localhost
# Redis服务器连接端口
  port: 6379
# Redis服务器连接密码（默认为空）
  password:
# 连接池最大连接数（使用负值表示没有限制）
  pool:
    max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
# 连接池中的最大空闲连接
    max-idle: 8
# 连接池中的最小空闲连接
    min-idle: 0
# 连接超时时间（毫秒）
  timeout: 0
# 打印sql
logging:
  level:
    com.bamboo.system.mapper: DEBUG