spring:
  application:
    name: quartz
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/knowledge
#    username: root
#    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8001

system:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowledge_system
    username: root
    password: 123456

school:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowledge_school
    username: root
    password: 123456


redis:
# Redis数据库索引（默认为0）
  database: 0
# Redis服务器地址
  host: localhost
# Redis服务器连接端口
  port: 6379
# Redis服务器连接密码（默认为空）
  password:
# 连接池最大连接数（使用负值表示没有限制）
  pool:
    max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
# 连接池中的最大空闲连接
    max-idle: 8
# 连接池中的最小空闲连接
    min-idle: 0
# 连接超时时间（毫秒）
  timeout: 0